### PR TITLE
Bundle and build fixes

### PR DESCRIPTION
**Pull request by cameronnorman**
- Ran `bundle update --bundler` to allow the application to operate
- Fixed dev build because it doesn't install the required bundler to bundle all the project gems

### CODE REVIEW

**Comment by cameronnorman** [comment]
Hey @casi. Please can you disable `travis.ci` in this repo settings

**Comment by casi** [comment]
@cameronnorman Sure, done.

**Review by casi — APPROVED** [review]
Nice, thanks!

**Review by casi — APPROVED** [review]

**Comment by cameronnorman** [comment]
@casi once reviewed and happy. Please merge so that I can start running gh actions when a PR is merged

**Pull request merged**
